# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 05:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocoding', '0002_auto_20180704_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='name',
            new_name='title',
        ),
    ]
